<?php

declare(strict_types=1);

/**
 * Catalogue ISO 4217 des devises actives (noms FR).
 * mode_arrondi: valeur de App\Referentiel\Domain\Enum\ModeArrondi.
 *
 * @return list<array{nom: string, code: string, mode_arrondi: string, decimales: int, symbole: string|null, unite_arrondi: string|null}>
 */
return [
    ['nom' => 'Dirham des Émirats arabes unis', 'code' => 'AED', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'د.إ', 'unite_arrondi' => null],
    ['nom' => 'Afghani', 'code' => 'AFN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '؋', 'unite_arrondi' => null],
    ['nom' => 'Lek albanais', 'code' => 'ALL', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'L', 'unite_arrondi' => null],
    ['nom' => 'Dram arménien', 'code' => 'AMD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '֏', 'unite_arrondi' => null],
    ['nom' => 'Florin des Antilles néerlandaises', 'code' => 'ANG', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'ƒ', 'unite_arrondi' => null],
    ['nom' => 'Kwanza angolais', 'code' => 'AOA', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Kz', 'unite_arrondi' => null],
    ['nom' => 'Peso argentin', 'code' => 'ARS', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '$', 'unite_arrondi' => null],
    ['nom' => 'Dollar australien', 'code' => 'AUD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'A$', 'unite_arrondi' => null],
    ['nom' => 'Florin arubais', 'code' => 'AWG', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'ƒ', 'unite_arrondi' => null],
    ['nom' => 'Manat azerbaïdjanais', 'code' => 'AZN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₼', 'unite_arrondi' => null],
    ['nom' => 'Mark convertible', 'code' => 'BAM', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'KM', 'unite_arrondi' => null],
    ['nom' => 'Dollar barbadien', 'code' => 'BBD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Bds$', 'unite_arrondi' => null],
    ['nom' => 'Taka bangladais', 'code' => 'BDT', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '৳', 'unite_arrondi' => null],
    ['nom' => 'Lev bulgare', 'code' => 'BGN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'лв', 'unite_arrondi' => null],
    ['nom' => 'Dinar bahreïni', 'code' => 'BHD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 3, 'symbole' => '.د.ب', 'unite_arrondi' => null],
    ['nom' => 'Franc burundais', 'code' => 'BIF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => 'FBu', 'unite_arrondi' => null],
    ['nom' => 'Dollar bermudien', 'code' => 'BMD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '$', 'unite_arrondi' => null],
    ['nom' => 'Dollar de Brunei', 'code' => 'BND', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'B$', 'unite_arrondi' => null],
    ['nom' => 'Boliviano', 'code' => 'BOB', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Bs', 'unite_arrondi' => null],
    ['nom' => 'Real brésilien', 'code' => 'BRL', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'R$', 'unite_arrondi' => null],
    ['nom' => 'Dollar bahaméen', 'code' => 'BSD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'B$', 'unite_arrondi' => null],
    ['nom' => 'Ngultrum bhoutanais', 'code' => 'BTN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Nu.', 'unite_arrondi' => null],
    ['nom' => 'Pula botswanais', 'code' => 'BWP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'P', 'unite_arrondi' => null],
    ['nom' => 'Rouble biélorusse', 'code' => 'BYN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Br', 'unite_arrondi' => null],
    ['nom' => 'Dollar bélizien', 'code' => 'BZD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'BZ$', 'unite_arrondi' => null],
    ['nom' => 'Dollar canadien', 'code' => 'CAD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'CA$', 'unite_arrondi' => null],
    ['nom' => 'Franc congolais', 'code' => 'CDF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'FC', 'unite_arrondi' => null],
    ['nom' => 'Franc suisse', 'code' => 'CHF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'CHF', 'unite_arrondi' => null],
    ['nom' => 'Peso chilien', 'code' => 'CLP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => '$', 'unite_arrondi' => null],
    ['nom' => 'Yuan chinois', 'code' => 'CNY', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '¥', 'unite_arrondi' => null],
    ['nom' => 'Peso colombien', 'code' => 'COP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '$', 'unite_arrondi' => null],
    ['nom' => 'Colón costaricain', 'code' => 'CRC', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₡', 'unite_arrondi' => null],
    ['nom' => 'Peso cubain', 'code' => 'CUP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '$', 'unite_arrondi' => null],
    ['nom' => 'Escudo cap-verdien', 'code' => 'CVE', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '$', 'unite_arrondi' => null],
    ['nom' => 'Couronne tchèque', 'code' => 'CZK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Kč', 'unite_arrondi' => null],
    ['nom' => 'Franc djiboutien', 'code' => 'DJF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => 'Fdj', 'unite_arrondi' => null],
    ['nom' => 'Couronne danoise', 'code' => 'DKK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'kr', 'unite_arrondi' => null],
    ['nom' => 'Peso dominicain', 'code' => 'DOP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'RD$', 'unite_arrondi' => null],
    ['nom' => 'Dinar algérien', 'code' => 'DZD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'د.ج', 'unite_arrondi' => null],
    ['nom' => 'Livre égyptienne', 'code' => 'EGP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'E£', 'unite_arrondi' => null],
    ['nom' => 'Nakfa érythréen', 'code' => 'ERN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Nfk', 'unite_arrondi' => null],
    ['nom' => 'Birr éthiopien', 'code' => 'ETB', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Br', 'unite_arrondi' => null],
    ['nom' => 'Euro', 'code' => 'EUR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '€', 'unite_arrondi' => null],
    ['nom' => 'Dollar fidjien', 'code' => 'FJD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'FJ$', 'unite_arrondi' => null],
    ['nom' => 'Livre des îles Malouines', 'code' => 'FKP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '£', 'unite_arrondi' => null],
    ['nom' => 'Livre sterling', 'code' => 'GBP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '£', 'unite_arrondi' => null],
    ['nom' => 'Lari géorgien', 'code' => 'GEL', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₾', 'unite_arrondi' => null],
    ['nom' => 'Cedi ghanéen', 'code' => 'GHS', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₵', 'unite_arrondi' => null],
    ['nom' => 'Livre de Gibraltar', 'code' => 'GIP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '£', 'unite_arrondi' => null],
    ['nom' => 'Dalasi gambien', 'code' => 'GMD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'D', 'unite_arrondi' => null],
    ['nom' => 'Franc guinéen', 'code' => 'GNF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => 'FG', 'unite_arrondi' => null],
    ['nom' => 'Quetzal guatémaltèque', 'code' => 'GTQ', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Q', 'unite_arrondi' => null],
    ['nom' => 'Dollar guyanien', 'code' => 'GYD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'G$', 'unite_arrondi' => null],
    ['nom' => 'Dollar de Hong Kong', 'code' => 'HKD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'HK$', 'unite_arrondi' => null],
    ['nom' => 'Lempira hondurien', 'code' => 'HNL', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'L', 'unite_arrondi' => null],
    ['nom' => 'Kuna croate', 'code' => 'HRK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'kn', 'unite_arrondi' => null],
    ['nom' => 'Gourde haïtienne', 'code' => 'HTG', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'G', 'unite_arrondi' => null],
    ['nom' => 'Forint hongrois', 'code' => 'HUF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Ft', 'unite_arrondi' => null],
    ['nom' => 'Roupie indonésienne', 'code' => 'IDR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Rp', 'unite_arrondi' => null],
    ['nom' => 'Shekel israélien', 'code' => 'ILS', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₪', 'unite_arrondi' => null],
    ['nom' => 'Roupie indienne', 'code' => 'INR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₹', 'unite_arrondi' => null],
    ['nom' => 'Dinar irakien', 'code' => 'IQD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 3, 'symbole' => 'ع.د', 'unite_arrondi' => null],
    ['nom' => 'Rial iranien', 'code' => 'IRR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '﷼', 'unite_arrondi' => null],
    ['nom' => 'Couronne islandaise', 'code' => 'ISK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => 'kr', 'unite_arrondi' => null],
    ['nom' => 'Dollar jamaïcain', 'code' => 'JMD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'J$', 'unite_arrondi' => null],
    ['nom' => 'Dinar jordanien', 'code' => 'JOD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 3, 'symbole' => 'د.ا', 'unite_arrondi' => null],
    ['nom' => 'Yen japonais', 'code' => 'JPY', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => '¥', 'unite_arrondi' => null],
    ['nom' => 'Shilling kényan', 'code' => 'KES', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'KSh', 'unite_arrondi' => null],
    ['nom' => 'Som kirghize', 'code' => 'KGS', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'с', 'unite_arrondi' => null],
    ['nom' => 'Riel cambodgien', 'code' => 'KHR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '៛', 'unite_arrondi' => null],
    ['nom' => 'Franc comorien', 'code' => 'KMF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => 'CF', 'unite_arrondi' => null],
    ['nom' => 'Won nord-coréen', 'code' => 'KPW', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₩', 'unite_arrondi' => null],
    ['nom' => 'Won sud-coréen', 'code' => 'KRW', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => '₩', 'unite_arrondi' => null],
    ['nom' => 'Dinar koweïtien', 'code' => 'KWD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 3, 'symbole' => 'د.ك', 'unite_arrondi' => null],
    ['nom' => 'Dollar des îles Caïmans', 'code' => 'KYD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'CI$', 'unite_arrondi' => null],
    ['nom' => 'Tenge kazakh', 'code' => 'KZT', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₸', 'unite_arrondi' => null],
    ['nom' => 'Kip laotien', 'code' => 'LAK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₭', 'unite_arrondi' => null],
    ['nom' => 'Livre libanaise', 'code' => 'LBP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'ل.ل', 'unite_arrondi' => null],
    ['nom' => 'Roupie srilankaise', 'code' => 'LKR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Rs', 'unite_arrondi' => null],
    ['nom' => 'Dollar libérien', 'code' => 'LRD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'L$', 'unite_arrondi' => null],
    ['nom' => 'Loti lesothan', 'code' => 'LSL', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'L', 'unite_arrondi' => null],
    ['nom' => 'Dinar libyen', 'code' => 'LYD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 3, 'symbole' => 'ل.د', 'unite_arrondi' => null],
    ['nom' => 'Dirham marocain', 'code' => 'MAD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'د.م.', 'unite_arrondi' => null],
    ['nom' => 'Leu moldave', 'code' => 'MDL', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'L', 'unite_arrondi' => null],
    ['nom' => 'Ariary malgache', 'code' => 'MGA', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Ar', 'unite_arrondi' => null],
    ['nom' => 'Denar macédonien', 'code' => 'MKD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'ден', 'unite_arrondi' => null],
    ['nom' => 'Kyat myanmarais', 'code' => 'MMK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'K', 'unite_arrondi' => null],
    ['nom' => 'Tugrik mongol', 'code' => 'MNT', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₮', 'unite_arrondi' => null],
    ['nom' => 'Pataca macanaise', 'code' => 'MOP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'MOP$', 'unite_arrondi' => null],
    ['nom' => 'Ouguiya mauritanienne', 'code' => 'MRU', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'UM', 'unite_arrondi' => null],
    ['nom' => 'Roupie mauricienne', 'code' => 'MUR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₨', 'unite_arrondi' => null],
    ['nom' => 'Rufiyaa maldivienne', 'code' => 'MVR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Rf', 'unite_arrondi' => null],
    ['nom' => 'Kwacha malawite', 'code' => 'MWK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'MK', 'unite_arrondi' => null],
    ['nom' => 'Peso mexicain', 'code' => 'MXN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'MX$', 'unite_arrondi' => null],
    ['nom' => 'Ringgit malaisien', 'code' => 'MYR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'RM', 'unite_arrondi' => null],
    ['nom' => 'Metical mozambicain', 'code' => 'MZN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'MT', 'unite_arrondi' => null],
    ['nom' => 'Dollar namibien', 'code' => 'NAD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'N$', 'unite_arrondi' => null],
    ['nom' => 'Naira nigérian', 'code' => 'NGN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₦', 'unite_arrondi' => null],
    ['nom' => 'Córdoba nicaraguayen', 'code' => 'NIO', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'C$', 'unite_arrondi' => null],
    ['nom' => 'Couronne norvégienne', 'code' => 'NOK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'kr', 'unite_arrondi' => null],
    ['nom' => 'Roupie népalaise', 'code' => 'NPR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Rs', 'unite_arrondi' => null],
    ['nom' => 'Dollar néo-zélandais', 'code' => 'NZD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'NZ$', 'unite_arrondi' => null],
    ['nom' => 'Rial omanais', 'code' => 'OMR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 3, 'symbole' => 'ر.ع.', 'unite_arrondi' => null],
    ['nom' => 'Balboa panaméen', 'code' => 'PAB', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'B/.', 'unite_arrondi' => null],
    ['nom' => 'Sol péruvien', 'code' => 'PEN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'S/', 'unite_arrondi' => null],
    ['nom' => 'Kina papouasien', 'code' => 'PGK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'K', 'unite_arrondi' => null],
    ['nom' => 'Peso philippin', 'code' => 'PHP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₱', 'unite_arrondi' => null],
    ['nom' => 'Roupie pakistanaise', 'code' => 'PKR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₨', 'unite_arrondi' => null],
    ['nom' => 'Zloty polonais', 'code' => 'PLN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'zł', 'unite_arrondi' => null],
    ['nom' => 'Guarani paraguayen', 'code' => 'PYG', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => '₲', 'unite_arrondi' => null],
    ['nom' => 'Rial qatari', 'code' => 'QAR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'ر.ق', 'unite_arrondi' => null],
    ['nom' => 'Leu roumain', 'code' => 'RON', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'lei', 'unite_arrondi' => null],
    ['nom' => 'Dinar serbe', 'code' => 'RSD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'дин', 'unite_arrondi' => null],
    ['nom' => 'Rouble russe', 'code' => 'RUB', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₽', 'unite_arrondi' => null],
    ['nom' => 'Franc rwandais', 'code' => 'RWF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => 'FRw', 'unite_arrondi' => null],
    ['nom' => 'Riyal saoudien', 'code' => 'SAR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'ر.س', 'unite_arrondi' => null],
    ['nom' => 'Dollar des îles Salomon', 'code' => 'SBD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'SI$', 'unite_arrondi' => null],
    ['nom' => 'Roupie seychelloise', 'code' => 'SCR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₨', 'unite_arrondi' => null],
    ['nom' => 'Livre soudanaise', 'code' => 'SDG', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'ج.س.', 'unite_arrondi' => null],
    ['nom' => 'Couronne suédoise', 'code' => 'SEK', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'kr', 'unite_arrondi' => null],
    ['nom' => 'Dollar de Singapour', 'code' => 'SGD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'S$', 'unite_arrondi' => null],
    ['nom' => 'Livre de Sainte-Hélène', 'code' => 'SHP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '£', 'unite_arrondi' => null],
    ['nom' => 'Leone sierra-léonais', 'code' => 'SLE', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Le', 'unite_arrondi' => null],
    ['nom' => 'Shilling somalien', 'code' => 'SOS', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Sh', 'unite_arrondi' => null],
    ['nom' => 'Dollar surinamais', 'code' => 'SRD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '$', 'unite_arrondi' => null],
    ['nom' => 'Livre sud-soudanaise', 'code' => 'SSP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '£', 'unite_arrondi' => null],
    ['nom' => 'Dobra santoméenne', 'code' => 'STN', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Db', 'unite_arrondi' => null],
    ['nom' => 'Livre syrienne', 'code' => 'SYP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '£S', 'unite_arrondi' => null],
    ['nom' => 'Lilangeni swazi', 'code' => 'SZL', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'E', 'unite_arrondi' => null],
    ['nom' => 'Baht thaïlandais', 'code' => 'THB', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '฿', 'unite_arrondi' => null],
    ['nom' => 'Somoni tadjik', 'code' => 'TJS', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'SM', 'unite_arrondi' => null],
    ['nom' => 'Manat turkmène', 'code' => 'TMT', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'm', 'unite_arrondi' => null],
    ['nom' => 'Dinar tunisien', 'code' => 'TND', 'mode_arrondi' => 'HALF_UP', 'decimales' => 3, 'symbole' => 'د.ت', 'unite_arrondi' => null],
    ['nom' => 'Paʻanga tongien', 'code' => 'TOP', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'T$', 'unite_arrondi' => null],
    ['nom' => 'Livre turque', 'code' => 'TRY', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₺', 'unite_arrondi' => null],
    ['nom' => 'Dollar trinidadien', 'code' => 'TTD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'TT$', 'unite_arrondi' => null],
    ['nom' => 'Dollar taïwanais', 'code' => 'TWD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'NT$', 'unite_arrondi' => null],
    ['nom' => 'Shilling tanzanien', 'code' => 'TZS', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'TSh', 'unite_arrondi' => null],
    ['nom' => 'Hryvnia ukrainienne', 'code' => 'UAH', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '₴', 'unite_arrondi' => null],
    ['nom' => 'Shilling ougandais', 'code' => 'UGX', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => 'USh', 'unite_arrondi' => null],
    ['nom' => 'Dollar US', 'code' => 'USD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '$', 'unite_arrondi' => null],
    ['nom' => 'Peso uruguayen', 'code' => 'UYU', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '$U', 'unite_arrondi' => null],
    ['nom' => 'Sum ouzbek', 'code' => 'UZS', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'soʻm', 'unite_arrondi' => null],
    ['nom' => 'Bolívar vénézuélien', 'code' => 'VES', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Bs.', 'unite_arrondi' => null],
    ['nom' => 'Dong vietnamien', 'code' => 'VND', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => '₫', 'unite_arrondi' => null],
    ['nom' => 'Vatu vanuatais', 'code' => 'VUV', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => 'VT', 'unite_arrondi' => null],
    ['nom' => 'Tala samoan', 'code' => 'WST', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'WS$', 'unite_arrondi' => null],
    ['nom' => 'Franc CFA (Central)', 'code' => 'XAF', 'mode_arrondi' => 'UNITE', 'decimales' => 0, 'symbole' => 'FCFA', 'unite_arrondi' => '5'],
    ['nom' => 'Dollar des Caraïbes orientales', 'code' => 'XCD', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'EC$', 'unite_arrondi' => null],
    ['nom' => 'Franc CFA (Ouest)', 'code' => 'XOF', 'mode_arrondi' => 'UNITE', 'decimales' => 0, 'symbole' => 'FCFA', 'unite_arrondi' => '5'],
    ['nom' => 'Franc CFP', 'code' => 'XPF', 'mode_arrondi' => 'HALF_UP', 'decimales' => 0, 'symbole' => '₣', 'unite_arrondi' => null],
    ['nom' => 'Rial yéménite', 'code' => 'YER', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => '﷼', 'unite_arrondi' => null],
    ['nom' => 'Rand sud-africain', 'code' => 'ZAR', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'R', 'unite_arrondi' => null],
    ['nom' => 'Kwacha zambien', 'code' => 'ZMW', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'ZK', 'unite_arrondi' => null],
    ['nom' => 'Dollar zimbabwéen', 'code' => 'ZWL', 'mode_arrondi' => 'HALF_UP', 'decimales' => 2, 'symbole' => 'Z$', 'unite_arrondi' => null],
];
