<?php

declare(strict_types=1);

/**
 * Catalogue ISO 3166-1 alpha-2 des pays (noms FR, indicatif E.164, devise officielle).
 *
 * @return list<array{nom: string, code: string, indicatif_telephonique: string|null, devise_defaut_code: string, devises_supportees: list<array{devise_code: string, taux_defaut: string, is_defaut: bool}>}>
 */
return [
    ['nom' => 'Andorre', 'code' => 'AD', 'indicatif_telephonique' => '+376', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Émirats arabes unis', 'code' => 'AE', 'indicatif_telephonique' => '+971', 'devise_defaut_code' => 'AED', 'devises_supportees' => []],
    ['nom' => 'Afghanistan', 'code' => 'AF', 'indicatif_telephonique' => '+93', 'devise_defaut_code' => 'AFN', 'devises_supportees' => []],
    ['nom' => 'Antigua-et-Barbuda', 'code' => 'AG', 'indicatif_telephonique' => '+1268', 'devise_defaut_code' => 'XCD', 'devises_supportees' => []],
    ['nom' => 'Albanie', 'code' => 'AL', 'indicatif_telephonique' => '+355', 'devise_defaut_code' => 'ALL', 'devises_supportees' => []],
    ['nom' => 'Arménie', 'code' => 'AM', 'indicatif_telephonique' => '+374', 'devise_defaut_code' => 'AMD', 'devises_supportees' => []],
    ['nom' => 'Angola', 'code' => 'AO', 'indicatif_telephonique' => '+244', 'devise_defaut_code' => 'AOA', 'devises_supportees' => []],
    ['nom' => 'Antarctique', 'code' => 'AQ', 'indicatif_telephonique' => null, 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Argentine', 'code' => 'AR', 'indicatif_telephonique' => '+54', 'devise_defaut_code' => 'ARS', 'devises_supportees' => []],
    ['nom' => 'Samoa américaines', 'code' => 'AS', 'indicatif_telephonique' => '+1684', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Autriche', 'code' => 'AT', 'indicatif_telephonique' => '+43', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Australie', 'code' => 'AU', 'indicatif_telephonique' => '+61', 'devise_defaut_code' => 'AUD', 'devises_supportees' => []],
    ['nom' => 'Aruba', 'code' => 'AW', 'indicatif_telephonique' => '+297', 'devise_defaut_code' => 'AWG', 'devises_supportees' => []],
    ['nom' => 'Îles Åland', 'code' => 'AX', 'indicatif_telephonique' => '+358', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Azerbaïdjan', 'code' => 'AZ', 'indicatif_telephonique' => '+994', 'devise_defaut_code' => 'AZN', 'devises_supportees' => []],
    ['nom' => 'Bosnie-Herzégovine', 'code' => 'BA', 'indicatif_telephonique' => '+387', 'devise_defaut_code' => 'BAM', 'devises_supportees' => []],
    ['nom' => 'Barbade', 'code' => 'BB', 'indicatif_telephonique' => '+1246', 'devise_defaut_code' => 'BBD', 'devises_supportees' => []],
    ['nom' => 'Bangladesh', 'code' => 'BD', 'indicatif_telephonique' => '+880', 'devise_defaut_code' => 'BDT', 'devises_supportees' => []],
    ['nom' => 'Belgique', 'code' => 'BE', 'indicatif_telephonique' => '+32', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Burkina Faso', 'code' => 'BF', 'indicatif_telephonique' => '+226', 'devise_defaut_code' => 'XOF', 'devises_supportees' => []],
    ['nom' => 'Bulgarie', 'code' => 'BG', 'indicatif_telephonique' => '+359', 'devise_defaut_code' => 'BGN', 'devises_supportees' => []],
    ['nom' => 'Bahreïn', 'code' => 'BH', 'indicatif_telephonique' => '+973', 'devise_defaut_code' => 'BHD', 'devises_supportees' => []],
    ['nom' => 'Burundi', 'code' => 'BI', 'indicatif_telephonique' => '+257', 'devise_defaut_code' => 'BIF', 'devises_supportees' => []],
    ['nom' => 'Bénin', 'code' => 'BJ', 'indicatif_telephonique' => '+229', 'devise_defaut_code' => 'XOF', 'devises_supportees' => []],
    ['nom' => 'Saint-Barthélemy', 'code' => 'BL', 'indicatif_telephonique' => '+590', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Bermudes', 'code' => 'BM', 'indicatif_telephonique' => '+1441', 'devise_defaut_code' => 'BMD', 'devises_supportees' => []],
    ['nom' => 'Brunei', 'code' => 'BN', 'indicatif_telephonique' => '+673', 'devise_defaut_code' => 'BND', 'devises_supportees' => []],
    ['nom' => 'Bolivie', 'code' => 'BO', 'indicatif_telephonique' => '+591', 'devise_defaut_code' => 'BOB', 'devises_supportees' => []],
    ['nom' => 'Bonaire, Saint-Eustache et Saba', 'code' => 'BQ', 'indicatif_telephonique' => '+599', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Brésil', 'code' => 'BR', 'indicatif_telephonique' => '+55', 'devise_defaut_code' => 'BRL', 'devises_supportees' => []],
    ['nom' => 'Bahamas', 'code' => 'BS', 'indicatif_telephonique' => '+1242', 'devise_defaut_code' => 'BSD', 'devises_supportees' => []],
    ['nom' => 'Bhoutan', 'code' => 'BT', 'indicatif_telephonique' => '+975', 'devise_defaut_code' => 'BTN', 'devises_supportees' => []],
    ['nom' => 'Île Bouvet', 'code' => 'BV', 'indicatif_telephonique' => null, 'devise_defaut_code' => 'NOK', 'devises_supportees' => []],
    ['nom' => 'Botswana', 'code' => 'BW', 'indicatif_telephonique' => '+267', 'devise_defaut_code' => 'BWP', 'devises_supportees' => []],
    ['nom' => 'Biélorussie', 'code' => 'BY', 'indicatif_telephonique' => '+375', 'devise_defaut_code' => 'BYN', 'devises_supportees' => []],
    ['nom' => 'Belize', 'code' => 'BZ', 'indicatif_telephonique' => '+501', 'devise_defaut_code' => 'BZD', 'devises_supportees' => []],
    ['nom' => 'Canada', 'code' => 'CA', 'indicatif_telephonique' => '+1', 'devise_defaut_code' => 'CAD', 'devises_supportees' => []],
    ['nom' => 'Îles Cocos', 'code' => 'CC', 'indicatif_telephonique' => '+61', 'devise_defaut_code' => 'AUD', 'devises_supportees' => []],
    ['nom' => 'République démocratique du Congo', 'code' => 'CD', 'indicatif_telephonique' => '+243', 'devise_defaut_code' => 'CDF', 'devises_supportees' => []],
    ['nom' => 'République centrafricaine', 'code' => 'CF', 'indicatif_telephonique' => '+236', 'devise_defaut_code' => 'XAF', 'devises_supportees' => []],
    ['nom' => 'Congo', 'code' => 'CG', 'indicatif_telephonique' => '+242', 'devise_defaut_code' => 'XAF', 'devises_supportees' => []],
    ['nom' => 'Suisse', 'code' => 'CH', 'indicatif_telephonique' => '+41', 'devise_defaut_code' => 'CHF', 'devises_supportees' => []],
    ['nom' => 'Côte d\'Ivoire', 'code' => 'CI', 'indicatif_telephonique' => '+225', 'devise_defaut_code' => 'XOF', 'devises_supportees' => []],
    ['nom' => 'Îles Cook', 'code' => 'CK', 'indicatif_telephonique' => '+682', 'devise_defaut_code' => 'NZD', 'devises_supportees' => []],
    ['nom' => 'Chili', 'code' => 'CL', 'indicatif_telephonique' => '+56', 'devise_defaut_code' => 'CLP', 'devises_supportees' => []],
    ['nom' => 'Cameroun', 'code' => 'CM', 'indicatif_telephonique' => '+237', 'devise_defaut_code' => 'XAF', 'devises_supportees' => []],
    ['nom' => 'Chine', 'code' => 'CN', 'indicatif_telephonique' => '+86', 'devise_defaut_code' => 'CNY', 'devises_supportees' => [['devise_code' => 'CNY', 'taux_defaut' => '78.000000', 'is_defaut' => true]]],
    ['nom' => 'Colombie', 'code' => 'CO', 'indicatif_telephonique' => '+57', 'devise_defaut_code' => 'COP', 'devises_supportees' => []],
    ['nom' => 'Costa Rica', 'code' => 'CR', 'indicatif_telephonique' => '+506', 'devise_defaut_code' => 'CRC', 'devises_supportees' => []],
    ['nom' => 'Cuba', 'code' => 'CU', 'indicatif_telephonique' => '+53', 'devise_defaut_code' => 'CUP', 'devises_supportees' => []],
    ['nom' => 'Cap-Vert', 'code' => 'CV', 'indicatif_telephonique' => '+238', 'devise_defaut_code' => 'CVE', 'devises_supportees' => []],
    ['nom' => 'Curaçao', 'code' => 'CW', 'indicatif_telephonique' => '+599', 'devise_defaut_code' => 'ANG', 'devises_supportees' => []],
    ['nom' => 'Île Christmas', 'code' => 'CX', 'indicatif_telephonique' => '+61', 'devise_defaut_code' => 'AUD', 'devises_supportees' => []],
    ['nom' => 'Chypre', 'code' => 'CY', 'indicatif_telephonique' => '+357', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Tchéquie', 'code' => 'CZ', 'indicatif_telephonique' => '+420', 'devise_defaut_code' => 'CZK', 'devises_supportees' => []],
    ['nom' => 'Allemagne', 'code' => 'DE', 'indicatif_telephonique' => '+49', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Djibouti', 'code' => 'DJ', 'indicatif_telephonique' => '+253', 'devise_defaut_code' => 'DJF', 'devises_supportees' => []],
    ['nom' => 'Danemark', 'code' => 'DK', 'indicatif_telephonique' => '+45', 'devise_defaut_code' => 'DKK', 'devises_supportees' => []],
    ['nom' => 'Dominique', 'code' => 'DM', 'indicatif_telephonique' => '+1767', 'devise_defaut_code' => 'XCD', 'devises_supportees' => []],
    ['nom' => 'République dominicaine', 'code' => 'DO', 'indicatif_telephonique' => '+1809', 'devise_defaut_code' => 'DOP', 'devises_supportees' => []],
    ['nom' => 'Algérie', 'code' => 'DZ', 'indicatif_telephonique' => '+213', 'devise_defaut_code' => 'DZD', 'devises_supportees' => []],
    ['nom' => 'Équateur', 'code' => 'EC', 'indicatif_telephonique' => '+593', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Estonie', 'code' => 'EE', 'indicatif_telephonique' => '+372', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Égypte', 'code' => 'EG', 'indicatif_telephonique' => '+20', 'devise_defaut_code' => 'EGP', 'devises_supportees' => []],
    ['nom' => 'Sahara occidental', 'code' => 'EH', 'indicatif_telephonique' => '+212', 'devise_defaut_code' => 'MAD', 'devises_supportees' => []],
    ['nom' => 'Érythrée', 'code' => 'ER', 'indicatif_telephonique' => '+291', 'devise_defaut_code' => 'ERN', 'devises_supportees' => []],
    ['nom' => 'Espagne', 'code' => 'ES', 'indicatif_telephonique' => '+34', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Éthiopie', 'code' => 'ET', 'indicatif_telephonique' => '+251', 'devise_defaut_code' => 'ETB', 'devises_supportees' => []],
    ['nom' => 'Finlande', 'code' => 'FI', 'indicatif_telephonique' => '+358', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Fidji', 'code' => 'FJ', 'indicatif_telephonique' => '+679', 'devise_defaut_code' => 'FJD', 'devises_supportees' => []],
    ['nom' => 'Îles Malouines', 'code' => 'FK', 'indicatif_telephonique' => '+500', 'devise_defaut_code' => 'FKP', 'devises_supportees' => []],
    ['nom' => 'Micronésie', 'code' => 'FM', 'indicatif_telephonique' => '+691', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Îles Féroé', 'code' => 'FO', 'indicatif_telephonique' => '+298', 'devise_defaut_code' => 'DKK', 'devises_supportees' => []],
    ['nom' => 'France', 'code' => 'FR', 'indicatif_telephonique' => '+33', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Gabon', 'code' => 'GA', 'indicatif_telephonique' => '+241', 'devise_defaut_code' => 'XAF', 'devises_supportees' => []],
    ['nom' => 'Royaume-Uni', 'code' => 'GB', 'indicatif_telephonique' => '+44', 'devise_defaut_code' => 'GBP', 'devises_supportees' => []],
    ['nom' => 'Grenade', 'code' => 'GD', 'indicatif_telephonique' => '+1473', 'devise_defaut_code' => 'XCD', 'devises_supportees' => []],
    ['nom' => 'Géorgie', 'code' => 'GE', 'indicatif_telephonique' => '+995', 'devise_defaut_code' => 'GEL', 'devises_supportees' => []],
    ['nom' => 'Guyane française', 'code' => 'GF', 'indicatif_telephonique' => '+594', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Guernesey', 'code' => 'GG', 'indicatif_telephonique' => '+44', 'devise_defaut_code' => 'GBP', 'devises_supportees' => []],
    ['nom' => 'Ghana', 'code' => 'GH', 'indicatif_telephonique' => '+233', 'devise_defaut_code' => 'GHS', 'devises_supportees' => []],
    ['nom' => 'Gibraltar', 'code' => 'GI', 'indicatif_telephonique' => '+350', 'devise_defaut_code' => 'GIP', 'devises_supportees' => []],
    ['nom' => 'Groenland', 'code' => 'GL', 'indicatif_telephonique' => '+299', 'devise_defaut_code' => 'DKK', 'devises_supportees' => []],
    ['nom' => 'Gambie', 'code' => 'GM', 'indicatif_telephonique' => '+220', 'devise_defaut_code' => 'GMD', 'devises_supportees' => []],
    ['nom' => 'Guinée', 'code' => 'GN', 'indicatif_telephonique' => '+224', 'devise_defaut_code' => 'GNF', 'devises_supportees' => []],
    ['nom' => 'Guadeloupe', 'code' => 'GP', 'indicatif_telephonique' => '+590', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Guinée équatoriale', 'code' => 'GQ', 'indicatif_telephonique' => '+240', 'devise_defaut_code' => 'XAF', 'devises_supportees' => []],
    ['nom' => 'Grèce', 'code' => 'GR', 'indicatif_telephonique' => '+30', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Géorgie du Sud-et-les Îles Sandwich du Sud', 'code' => 'GS', 'indicatif_telephonique' => '+500', 'devise_defaut_code' => 'GBP', 'devises_supportees' => []],
    ['nom' => 'Guatemala', 'code' => 'GT', 'indicatif_telephonique' => '+502', 'devise_defaut_code' => 'GTQ', 'devises_supportees' => []],
    ['nom' => 'Guam', 'code' => 'GU', 'indicatif_telephonique' => '+1671', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Guinée-Bissau', 'code' => 'GW', 'indicatif_telephonique' => '+245', 'devise_defaut_code' => 'XOF', 'devises_supportees' => []],
    ['nom' => 'Guyana', 'code' => 'GY', 'indicatif_telephonique' => '+592', 'devise_defaut_code' => 'GYD', 'devises_supportees' => []],
    ['nom' => 'Hong Kong', 'code' => 'HK', 'indicatif_telephonique' => '+852', 'devise_defaut_code' => 'HKD', 'devises_supportees' => []],
    ['nom' => 'Îles Heard-et-MacDonald', 'code' => 'HM', 'indicatif_telephonique' => null, 'devise_defaut_code' => 'AUD', 'devises_supportees' => []],
    ['nom' => 'Honduras', 'code' => 'HN', 'indicatif_telephonique' => '+504', 'devise_defaut_code' => 'HNL', 'devises_supportees' => []],
    ['nom' => 'Croatie', 'code' => 'HR', 'indicatif_telephonique' => '+385', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Haïti', 'code' => 'HT', 'indicatif_telephonique' => '+509', 'devise_defaut_code' => 'HTG', 'devises_supportees' => []],
    ['nom' => 'Hongrie', 'code' => 'HU', 'indicatif_telephonique' => '+36', 'devise_defaut_code' => 'HUF', 'devises_supportees' => []],
    ['nom' => 'Indonésie', 'code' => 'ID', 'indicatif_telephonique' => '+62', 'devise_defaut_code' => 'IDR', 'devises_supportees' => []],
    ['nom' => 'Irlande', 'code' => 'IE', 'indicatif_telephonique' => '+353', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Israël', 'code' => 'IL', 'indicatif_telephonique' => '+972', 'devise_defaut_code' => 'ILS', 'devises_supportees' => []],
    ['nom' => 'Île de Man', 'code' => 'IM', 'indicatif_telephonique' => '+44', 'devise_defaut_code' => 'GBP', 'devises_supportees' => []],
    ['nom' => 'Inde', 'code' => 'IN', 'indicatif_telephonique' => '+91', 'devise_defaut_code' => 'INR', 'devises_supportees' => []],
    ['nom' => 'Territoire britannique de l\'océan Indien', 'code' => 'IO', 'indicatif_telephonique' => '+246', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Irak', 'code' => 'IQ', 'indicatif_telephonique' => '+964', 'devise_defaut_code' => 'IQD', 'devises_supportees' => []],
    ['nom' => 'Iran', 'code' => 'IR', 'indicatif_telephonique' => '+98', 'devise_defaut_code' => 'IRR', 'devises_supportees' => []],
    ['nom' => 'Islande', 'code' => 'IS', 'indicatif_telephonique' => '+354', 'devise_defaut_code' => 'ISK', 'devises_supportees' => []],
    ['nom' => 'Italie', 'code' => 'IT', 'indicatif_telephonique' => '+39', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Jersey', 'code' => 'JE', 'indicatif_telephonique' => '+44', 'devise_defaut_code' => 'GBP', 'devises_supportees' => []],
    ['nom' => 'Jamaïque', 'code' => 'JM', 'indicatif_telephonique' => '+1876', 'devise_defaut_code' => 'JMD', 'devises_supportees' => []],
    ['nom' => 'Jordanie', 'code' => 'JO', 'indicatif_telephonique' => '+962', 'devise_defaut_code' => 'JOD', 'devises_supportees' => []],
    ['nom' => 'Japon', 'code' => 'JP', 'indicatif_telephonique' => '+81', 'devise_defaut_code' => 'JPY', 'devises_supportees' => []],
    ['nom' => 'Kenya', 'code' => 'KE', 'indicatif_telephonique' => '+254', 'devise_defaut_code' => 'KES', 'devises_supportees' => []],
    ['nom' => 'Kirghizistan', 'code' => 'KG', 'indicatif_telephonique' => '+996', 'devise_defaut_code' => 'KGS', 'devises_supportees' => []],
    ['nom' => 'Cambodge', 'code' => 'KH', 'indicatif_telephonique' => '+855', 'devise_defaut_code' => 'KHR', 'devises_supportees' => []],
    ['nom' => 'Kiribati', 'code' => 'KI', 'indicatif_telephonique' => '+686', 'devise_defaut_code' => 'AUD', 'devises_supportees' => []],
    ['nom' => 'Comores', 'code' => 'KM', 'indicatif_telephonique' => '+269', 'devise_defaut_code' => 'KMF', 'devises_supportees' => []],
    ['nom' => 'Saint-Kitts-et-Nevis', 'code' => 'KN', 'indicatif_telephonique' => '+1869', 'devise_defaut_code' => 'XCD', 'devises_supportees' => []],
    ['nom' => 'Corée du Nord', 'code' => 'KP', 'indicatif_telephonique' => '+850', 'devise_defaut_code' => 'KPW', 'devises_supportees' => []],
    ['nom' => 'Corée du Sud', 'code' => 'KR', 'indicatif_telephonique' => '+82', 'devise_defaut_code' => 'KRW', 'devises_supportees' => []],
    ['nom' => 'Koweït', 'code' => 'KW', 'indicatif_telephonique' => '+965', 'devise_defaut_code' => 'KWD', 'devises_supportees' => []],
    ['nom' => 'Îles Caïmans', 'code' => 'KY', 'indicatif_telephonique' => '+1345', 'devise_defaut_code' => 'KYD', 'devises_supportees' => []],
    ['nom' => 'Kazakhstan', 'code' => 'KZ', 'indicatif_telephonique' => '+7', 'devise_defaut_code' => 'KZT', 'devises_supportees' => []],
    ['nom' => 'Laos', 'code' => 'LA', 'indicatif_telephonique' => '+856', 'devise_defaut_code' => 'LAK', 'devises_supportees' => []],
    ['nom' => 'Liban', 'code' => 'LB', 'indicatif_telephonique' => '+961', 'devise_defaut_code' => 'LBP', 'devises_supportees' => []],
    ['nom' => 'Sainte-Lucie', 'code' => 'LC', 'indicatif_telephonique' => '+1758', 'devise_defaut_code' => 'XCD', 'devises_supportees' => []],
    ['nom' => 'Liechtenstein', 'code' => 'LI', 'indicatif_telephonique' => '+423', 'devise_defaut_code' => 'CHF', 'devises_supportees' => []],
    ['nom' => 'Sri Lanka', 'code' => 'LK', 'indicatif_telephonique' => '+94', 'devise_defaut_code' => 'LKR', 'devises_supportees' => []],
    ['nom' => 'Libéria', 'code' => 'LR', 'indicatif_telephonique' => '+231', 'devise_defaut_code' => 'LRD', 'devises_supportees' => []],
    ['nom' => 'Lesotho', 'code' => 'LS', 'indicatif_telephonique' => '+266', 'devise_defaut_code' => 'LSL', 'devises_supportees' => []],
    ['nom' => 'Lituanie', 'code' => 'LT', 'indicatif_telephonique' => '+370', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Luxembourg', 'code' => 'LU', 'indicatif_telephonique' => '+352', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Lettonie', 'code' => 'LV', 'indicatif_telephonique' => '+371', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Libye', 'code' => 'LY', 'indicatif_telephonique' => '+218', 'devise_defaut_code' => 'LYD', 'devises_supportees' => []],
    ['nom' => 'Maroc', 'code' => 'MA', 'indicatif_telephonique' => '+212', 'devise_defaut_code' => 'MAD', 'devises_supportees' => []],
    ['nom' => 'Monaco', 'code' => 'MC', 'indicatif_telephonique' => '+377', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Moldavie', 'code' => 'MD', 'indicatif_telephonique' => '+373', 'devise_defaut_code' => 'MDL', 'devises_supportees' => []],
    ['nom' => 'Monténégro', 'code' => 'ME', 'indicatif_telephonique' => '+382', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Saint-Martin', 'code' => 'MF', 'indicatif_telephonique' => '+590', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Madagascar', 'code' => 'MG', 'indicatif_telephonique' => '+261', 'devise_defaut_code' => 'MGA', 'devises_supportees' => []],
    ['nom' => 'Îles Marshall', 'code' => 'MH', 'indicatif_telephonique' => '+692', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Macédoine du Nord', 'code' => 'MK', 'indicatif_telephonique' => '+389', 'devise_defaut_code' => 'MKD', 'devises_supportees' => []],
    ['nom' => 'Mali', 'code' => 'ML', 'indicatif_telephonique' => '+223', 'devise_defaut_code' => 'XOF', 'devises_supportees' => []],
    ['nom' => 'Myanmar', 'code' => 'MM', 'indicatif_telephonique' => '+95', 'devise_defaut_code' => 'MMK', 'devises_supportees' => []],
    ['nom' => 'Mongolie', 'code' => 'MN', 'indicatif_telephonique' => '+976', 'devise_defaut_code' => 'MNT', 'devises_supportees' => []],
    ['nom' => 'Macao', 'code' => 'MO', 'indicatif_telephonique' => '+853', 'devise_defaut_code' => 'MOP', 'devises_supportees' => []],
    ['nom' => 'Îles Mariannes du Nord', 'code' => 'MP', 'indicatif_telephonique' => '+1670', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Martinique', 'code' => 'MQ', 'indicatif_telephonique' => '+596', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Mauritanie', 'code' => 'MR', 'indicatif_telephonique' => '+222', 'devise_defaut_code' => 'MRU', 'devises_supportees' => []],
    ['nom' => 'Malte', 'code' => 'MT', 'indicatif_telephonique' => '+356', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Maurice', 'code' => 'MU', 'indicatif_telephonique' => '+230', 'devise_defaut_code' => 'MUR', 'devises_supportees' => []],
    ['nom' => 'Maldives', 'code' => 'MV', 'indicatif_telephonique' => '+960', 'devise_defaut_code' => 'MVR', 'devises_supportees' => []],
    ['nom' => 'Malawi', 'code' => 'MW', 'indicatif_telephonique' => '+265', 'devise_defaut_code' => 'MWK', 'devises_supportees' => []],
    ['nom' => 'Mexique', 'code' => 'MX', 'indicatif_telephonique' => '+52', 'devise_defaut_code' => 'MXN', 'devises_supportees' => []],
    ['nom' => 'Malaisie', 'code' => 'MY', 'indicatif_telephonique' => '+60', 'devise_defaut_code' => 'MYR', 'devises_supportees' => []],
    ['nom' => 'Mozambique', 'code' => 'MZ', 'indicatif_telephonique' => '+258', 'devise_defaut_code' => 'MZN', 'devises_supportees' => []],
    ['nom' => 'Namibie', 'code' => 'NA', 'indicatif_telephonique' => '+264', 'devise_defaut_code' => 'NAD', 'devises_supportees' => []],
    ['nom' => 'Nouvelle-Calédonie', 'code' => 'NC', 'indicatif_telephonique' => '+687', 'devise_defaut_code' => 'XPF', 'devises_supportees' => []],
    ['nom' => 'Niger', 'code' => 'NE', 'indicatif_telephonique' => '+227', 'devise_defaut_code' => 'XOF', 'devises_supportees' => []],
    ['nom' => 'Île Norfolk', 'code' => 'NF', 'indicatif_telephonique' => '+672', 'devise_defaut_code' => 'AUD', 'devises_supportees' => []],
    ['nom' => 'Nigeria', 'code' => 'NG', 'indicatif_telephonique' => '+234', 'devise_defaut_code' => 'NGN', 'devises_supportees' => []],
    ['nom' => 'Nicaragua', 'code' => 'NI', 'indicatif_telephonique' => '+505', 'devise_defaut_code' => 'NIO', 'devises_supportees' => []],
    ['nom' => 'Pays-Bas', 'code' => 'NL', 'indicatif_telephonique' => '+31', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Norvège', 'code' => 'NO', 'indicatif_telephonique' => '+47', 'devise_defaut_code' => 'NOK', 'devises_supportees' => []],
    ['nom' => 'Népal', 'code' => 'NP', 'indicatif_telephonique' => '+977', 'devise_defaut_code' => 'NPR', 'devises_supportees' => []],
    ['nom' => 'Nauru', 'code' => 'NR', 'indicatif_telephonique' => '+674', 'devise_defaut_code' => 'AUD', 'devises_supportees' => []],
    ['nom' => 'Niue', 'code' => 'NU', 'indicatif_telephonique' => '+683', 'devise_defaut_code' => 'NZD', 'devises_supportees' => []],
    ['nom' => 'Nouvelle-Zélande', 'code' => 'NZ', 'indicatif_telephonique' => '+64', 'devise_defaut_code' => 'NZD', 'devises_supportees' => []],
    ['nom' => 'Oman', 'code' => 'OM', 'indicatif_telephonique' => '+968', 'devise_defaut_code' => 'OMR', 'devises_supportees' => []],
    ['nom' => 'Panama', 'code' => 'PA', 'indicatif_telephonique' => '+507', 'devise_defaut_code' => 'PAB', 'devises_supportees' => []],
    ['nom' => 'Pérou', 'code' => 'PE', 'indicatif_telephonique' => '+51', 'devise_defaut_code' => 'PEN', 'devises_supportees' => []],
    ['nom' => 'Polynésie française', 'code' => 'PF', 'indicatif_telephonique' => '+689', 'devise_defaut_code' => 'XPF', 'devises_supportees' => []],
    ['nom' => 'Papouasie-Nouvelle-Guinée', 'code' => 'PG', 'indicatif_telephonique' => '+675', 'devise_defaut_code' => 'PGK', 'devises_supportees' => []],
    ['nom' => 'Philippines', 'code' => 'PH', 'indicatif_telephonique' => '+63', 'devise_defaut_code' => 'PHP', 'devises_supportees' => []],
    ['nom' => 'Pakistan', 'code' => 'PK', 'indicatif_telephonique' => '+92', 'devise_defaut_code' => 'PKR', 'devises_supportees' => []],
    ['nom' => 'Pologne', 'code' => 'PL', 'indicatif_telephonique' => '+48', 'devise_defaut_code' => 'PLN', 'devises_supportees' => []],
    ['nom' => 'Saint-Pierre-et-Miquelon', 'code' => 'PM', 'indicatif_telephonique' => '+508', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Îles Pitcairn', 'code' => 'PN', 'indicatif_telephonique' => '+64', 'devise_defaut_code' => 'NZD', 'devises_supportees' => []],
    ['nom' => 'Porto Rico', 'code' => 'PR', 'indicatif_telephonique' => '+1787', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Palestine', 'code' => 'PS', 'indicatif_telephonique' => '+970', 'devise_defaut_code' => 'ILS', 'devises_supportees' => []],
    ['nom' => 'Portugal', 'code' => 'PT', 'indicatif_telephonique' => '+351', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Palaos', 'code' => 'PW', 'indicatif_telephonique' => '+680', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Paraguay', 'code' => 'PY', 'indicatif_telephonique' => '+595', 'devise_defaut_code' => 'PYG', 'devises_supportees' => []],
    ['nom' => 'Qatar', 'code' => 'QA', 'indicatif_telephonique' => '+974', 'devise_defaut_code' => 'QAR', 'devises_supportees' => []],
    ['nom' => 'La Réunion', 'code' => 'RE', 'indicatif_telephonique' => '+262', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Roumanie', 'code' => 'RO', 'indicatif_telephonique' => '+40', 'devise_defaut_code' => 'RON', 'devises_supportees' => []],
    ['nom' => 'Serbie', 'code' => 'RS', 'indicatif_telephonique' => '+381', 'devise_defaut_code' => 'RSD', 'devises_supportees' => []],
    ['nom' => 'Russie', 'code' => 'RU', 'indicatif_telephonique' => '+7', 'devise_defaut_code' => 'RUB', 'devises_supportees' => []],
    ['nom' => 'Rwanda', 'code' => 'RW', 'indicatif_telephonique' => '+250', 'devise_defaut_code' => 'RWF', 'devises_supportees' => []],
    ['nom' => 'Arabie saoudite', 'code' => 'SA', 'indicatif_telephonique' => '+966', 'devise_defaut_code' => 'SAR', 'devises_supportees' => []],
    ['nom' => 'Îles Salomon', 'code' => 'SB', 'indicatif_telephonique' => '+677', 'devise_defaut_code' => 'SBD', 'devises_supportees' => []],
    ['nom' => 'Seychelles', 'code' => 'SC', 'indicatif_telephonique' => '+248', 'devise_defaut_code' => 'SCR', 'devises_supportees' => []],
    ['nom' => 'Soudan', 'code' => 'SD', 'indicatif_telephonique' => '+249', 'devise_defaut_code' => 'SDG', 'devises_supportees' => []],
    ['nom' => 'Suède', 'code' => 'SE', 'indicatif_telephonique' => '+46', 'devise_defaut_code' => 'SEK', 'devises_supportees' => []],
    ['nom' => 'Singapour', 'code' => 'SG', 'indicatif_telephonique' => '+65', 'devise_defaut_code' => 'SGD', 'devises_supportees' => []],
    ['nom' => 'Sainte-Hélène', 'code' => 'SH', 'indicatif_telephonique' => '+290', 'devise_defaut_code' => 'SHP', 'devises_supportees' => []],
    ['nom' => 'Slovénie', 'code' => 'SI', 'indicatif_telephonique' => '+386', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Svalbard et Jan Mayen', 'code' => 'SJ', 'indicatif_telephonique' => '+47', 'devise_defaut_code' => 'NOK', 'devises_supportees' => []],
    ['nom' => 'Slovaquie', 'code' => 'SK', 'indicatif_telephonique' => '+421', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Sierra Leone', 'code' => 'SL', 'indicatif_telephonique' => '+232', 'devise_defaut_code' => 'SLE', 'devises_supportees' => []],
    ['nom' => 'Saint-Marin', 'code' => 'SM', 'indicatif_telephonique' => '+378', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Sénégal', 'code' => 'SN', 'indicatif_telephonique' => '+221', 'devise_defaut_code' => 'XOF', 'devises_supportees' => []],
    ['nom' => 'Somalie', 'code' => 'SO', 'indicatif_telephonique' => '+252', 'devise_defaut_code' => 'SOS', 'devises_supportees' => []],
    ['nom' => 'Suriname', 'code' => 'SR', 'indicatif_telephonique' => '+597', 'devise_defaut_code' => 'SRD', 'devises_supportees' => []],
    ['nom' => 'Soudan du Sud', 'code' => 'SS', 'indicatif_telephonique' => '+211', 'devise_defaut_code' => 'SSP', 'devises_supportees' => []],
    ['nom' => 'Sao Tomé-et-Principe', 'code' => 'ST', 'indicatif_telephonique' => '+239', 'devise_defaut_code' => 'STN', 'devises_supportees' => []],
    ['nom' => 'Salvador', 'code' => 'SV', 'indicatif_telephonique' => '+503', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Sint Maarten', 'code' => 'SX', 'indicatif_telephonique' => '+1721', 'devise_defaut_code' => 'ANG', 'devises_supportees' => []],
    ['nom' => 'Syrie', 'code' => 'SY', 'indicatif_telephonique' => '+963', 'devise_defaut_code' => 'SYP', 'devises_supportees' => []],
    ['nom' => 'Eswatini', 'code' => 'SZ', 'indicatif_telephonique' => '+268', 'devise_defaut_code' => 'SZL', 'devises_supportees' => []],
    ['nom' => 'Îles Turques-et-Caïques', 'code' => 'TC', 'indicatif_telephonique' => '+1649', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Tchad', 'code' => 'TD', 'indicatif_telephonique' => '+235', 'devise_defaut_code' => 'XAF', 'devises_supportees' => []],
    ['nom' => 'Terres australes françaises', 'code' => 'TF', 'indicatif_telephonique' => null, 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Togo', 'code' => 'TG', 'indicatif_telephonique' => '+228', 'devise_defaut_code' => 'XOF', 'devises_supportees' => []],
    ['nom' => 'Thaïlande', 'code' => 'TH', 'indicatif_telephonique' => '+66', 'devise_defaut_code' => 'THB', 'devises_supportees' => []],
    ['nom' => 'Tadjikistan', 'code' => 'TJ', 'indicatif_telephonique' => '+992', 'devise_defaut_code' => 'TJS', 'devises_supportees' => []],
    ['nom' => 'Tokelau', 'code' => 'TK', 'indicatif_telephonique' => '+690', 'devise_defaut_code' => 'NZD', 'devises_supportees' => []],
    ['nom' => 'Timor oriental', 'code' => 'TL', 'indicatif_telephonique' => '+670', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Turkménistan', 'code' => 'TM', 'indicatif_telephonique' => '+993', 'devise_defaut_code' => 'TMT', 'devises_supportees' => []],
    ['nom' => 'Tunisie', 'code' => 'TN', 'indicatif_telephonique' => '+216', 'devise_defaut_code' => 'TND', 'devises_supportees' => []],
    ['nom' => 'Tonga', 'code' => 'TO', 'indicatif_telephonique' => '+676', 'devise_defaut_code' => 'TOP', 'devises_supportees' => []],
    ['nom' => 'Turquie', 'code' => 'TR', 'indicatif_telephonique' => '+90', 'devise_defaut_code' => 'TRY', 'devises_supportees' => []],
    ['nom' => 'Trinité-et-Tobago', 'code' => 'TT', 'indicatif_telephonique' => '+1868', 'devise_defaut_code' => 'TTD', 'devises_supportees' => []],
    ['nom' => 'Tuvalu', 'code' => 'TV', 'indicatif_telephonique' => '+688', 'devise_defaut_code' => 'AUD', 'devises_supportees' => []],
    ['nom' => 'Taïwan', 'code' => 'TW', 'indicatif_telephonique' => '+886', 'devise_defaut_code' => 'TWD', 'devises_supportees' => []],
    ['nom' => 'Tanzanie', 'code' => 'TZ', 'indicatif_telephonique' => '+255', 'devise_defaut_code' => 'TZS', 'devises_supportees' => []],
    ['nom' => 'Ukraine', 'code' => 'UA', 'indicatif_telephonique' => '+380', 'devise_defaut_code' => 'UAH', 'devises_supportees' => []],
    ['nom' => 'Ouganda', 'code' => 'UG', 'indicatif_telephonique' => '+256', 'devise_defaut_code' => 'UGX', 'devises_supportees' => []],
    ['nom' => 'Îles mineures éloignées des États-Unis', 'code' => 'UM', 'indicatif_telephonique' => null, 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'États-Unis', 'code' => 'US', 'indicatif_telephonique' => '+1', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Uruguay', 'code' => 'UY', 'indicatif_telephonique' => '+598', 'devise_defaut_code' => 'UYU', 'devises_supportees' => []],
    ['nom' => 'Ouzbékistan', 'code' => 'UZ', 'indicatif_telephonique' => '+998', 'devise_defaut_code' => 'UZS', 'devises_supportees' => []],
    ['nom' => 'Vatican', 'code' => 'VA', 'indicatif_telephonique' => '+379', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Saint-Vincent-et-les-Grenadines', 'code' => 'VC', 'indicatif_telephonique' => '+1784', 'devise_defaut_code' => 'XCD', 'devises_supportees' => []],
    ['nom' => 'Venezuela', 'code' => 'VE', 'indicatif_telephonique' => '+58', 'devise_defaut_code' => 'VES', 'devises_supportees' => []],
    ['nom' => 'Îles Vierges britanniques', 'code' => 'VG', 'indicatif_telephonique' => '+1284', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Îles Vierges américaines', 'code' => 'VI', 'indicatif_telephonique' => '+1340', 'devise_defaut_code' => 'USD', 'devises_supportees' => []],
    ['nom' => 'Viêt Nam', 'code' => 'VN', 'indicatif_telephonique' => '+84', 'devise_defaut_code' => 'VND', 'devises_supportees' => []],
    ['nom' => 'Vanuatu', 'code' => 'VU', 'indicatif_telephonique' => '+678', 'devise_defaut_code' => 'VUV', 'devises_supportees' => []],
    ['nom' => 'Wallis-et-Futuna', 'code' => 'WF', 'indicatif_telephonique' => '+681', 'devise_defaut_code' => 'XPF', 'devises_supportees' => []],
    ['nom' => 'Samoa', 'code' => 'WS', 'indicatif_telephonique' => '+685', 'devise_defaut_code' => 'WST', 'devises_supportees' => []],
    ['nom' => 'Kosovo', 'code' => 'XK', 'indicatif_telephonique' => '+383', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Yémen', 'code' => 'YE', 'indicatif_telephonique' => '+967', 'devise_defaut_code' => 'YER', 'devises_supportees' => []],
    ['nom' => 'Mayotte', 'code' => 'YT', 'indicatif_telephonique' => '+262', 'devise_defaut_code' => 'EUR', 'devises_supportees' => []],
    ['nom' => 'Afrique du Sud', 'code' => 'ZA', 'indicatif_telephonique' => '+27', 'devise_defaut_code' => 'ZAR', 'devises_supportees' => []],
    ['nom' => 'Zambie', 'code' => 'ZM', 'indicatif_telephonique' => '+260', 'devise_defaut_code' => 'ZMW', 'devises_supportees' => []],
    ['nom' => 'Zimbabwe', 'code' => 'ZW', 'indicatif_telephonique' => '+263', 'devise_defaut_code' => 'ZWL', 'devises_supportees' => []],
];
